nugraph/nugraph

- nugraph/models/decoders.py
"True label" and "Assigned label" labels were incorrectly flipped in confusion matrices; this PR swaps them.
> fix flipped axis labels for confusion matrices

- nugraph/models/decoders.py
This reverts commit 1a7e998d94380582f5d804acf4955292251b4c0c.
nevermind – the axes were actually correct to begin with 🙃
> Revert "fix flipped axis labels for confusion matrices"

- nugraph/models/nugraph2/NuGraph2.py
- nugraph/models/nugraph2/nexus.py
- nugraph/models/nugraph3/nexus.py
make a minor syntax tweak to the nexus convolution block that was causing an error under PyG 2.5. also remove a couple of defunct arguments that were throwing errors when training the NuGraph2 variant.
> Update for PyG 2.5

- nugraph/data/H5DataModule.py
fix a bug where the validation samples were being loaded for both the validation and test datasets. in order to preserve the events in the testing dataset as described in the paper, the validation and samples have been swapped in the `NG2-paper.gnn.h5` data file. the combination of these two changes should mean that from the user's perspective, the events in the validation dataset will change while the testing dataset will remain the same.
> fix loading of test dataset

- nugraph/nugraph/models/nugraph3/encoder.py
remove encoding of nexus node input positions, as they are not present in all datasets and they don't seem to improve final resolution of predicted vertex
> remove nexus input positions

- nugraph/nugraph/models/nugraph3/nugraph3.py
fixing a minor syntax bug that managed to sneak past our checks
> fix syntax bug in NuGraph3

- nugraph/nugraph/models/nugraph3/decoders/instance.py
add extra block to materialize function in the instance decoder, taking the instance edges and collapsing them down to a predicted instance label on each hit.
> added code to materialize predicted instance labels

- nugraph/nugraph/models/nugraph3/core.py
- nugraph/nugraph/models/nugraph3/decoders/event.py
- nugraph/nugraph/models/nugraph3/decoders/filter.py
- nugraph/nugraph/models/nugraph3/decoders/instance.py
- nugraph/nugraph/models/nugraph3/decoders/semantic.py
- nugraph/nugraph/models/nugraph3/encoder.py
- nugraph/nugraph/models/nugraph3/nugraph3.py
- nugraph/nugraph/util/hierarchical_edges.py
- pynuml/pynuml/process/hitgraph.py
restructure the graph data object to unify the planar hit node stores into a single node store. the connectivity of the graph edges remains the same. since the hit nodes are in a single node store, we no longer need `HeteroConv` for message-passing, so the model architecture has been simplified accordingly.
the graph restructure is implemented in the hierarchical feature transform, so existing graph objects will be updated to the new structure. graph processing in pynuml has also been updated, so future processing runs will produce this structure natively.
closes #84
> restructure graph object

- nugraph/nugraph/models/nugraph3/decoders/vertex.py
under the current implementation, aggregating training and validation metrics under `vertex/resolution-*` would pull in all the individual coordinate metrics too. restructuring in this way solves that issue.
> rename vertex metric to make grouping easier in wandb

- pynuml/pynuml/io/file.py
Skip the event whose ID is less than the minimal in a table.
> Bug fix: check against the minimal event ID

- pynuml/pynuml/io/file.py
When checking if a seq ID is missing, add a checking of whether the self._seq_cnt is empty. Empty self._seq_cnt most likely happens only when calling read_data(), rather than read_data_all()
> bug fix: short circuit if self._seq_cnt is empty

- .vscode/settings.json
- notebooks/make-test-file.ipynb
- notebooks/plot.ipynb
- notebooks/train.ipynb
- nugraph/nugraph/__init__.py
- nugraph/nugraph/data/H5DataModule.py
- nugraph/nugraph/models/nugraph3/core.py
- nugraph/nugraph/models/nugraph3/decoders/filter.py
- nugraph/nugraph/models/nugraph3/decoders/instance.py
- nugraph/nugraph/models/nugraph3/nugraph3.py
- nugraph/nugraph/models/nugraph3/types.py
- nugraph/nugraph/util/ObjCondensationLoss.py
- nugraph/nugraph/util/__init__.py
- nugraph/nugraph/util/hierarchical_edges.py
- nugraph/nugraph/util/scriptutils.py
- nugraph/pyproject.toml
- numl.yaml
- pynuml/pynuml/io/file.py
- pynuml/pynuml/plot/graph.py
- pynuml/pynuml/process/hitgraph.py
- pynuml/tests/test_process.py
- scripts/train.py
this feature branch overhauls how the instance decoder operates. the original scope of this work was to implement the adjusted Rand score (ARS) metric for clustering, but that work uncovered an issue with how we were performing clustering, so the scope has now expanded out to fixing that issue by redesigning pieces of the workflow
after adding code to materialize predicted instance labels and calculate the ARS, i noticed that the model wasn't training well – and in fact, was returning nonsense values for that metric. the ARS metric ranges between -1 and 1 by construction, but we were logging values as extreme as 20. i dug into the code, and realized it was due to an oversight in how we construct the instance truth.
up until now, instance labels have been implemented as an integer tensor …
> improvements to clustering

- pynuml/pynuml/io/file.py
if the size of the data array is zero, then the empty array will not have the correct dimensions. this PR adds a workaround to ensure the array has the correct size even when it has no contents.
> ensure array has correct shape if empty

- pynuml/pynuml/io/file.py
This PR fixes a missed check for when the size of a table's event_id.seq_cnt is
smaller than the requested event ID.
> Bug fix: check the array size if is smaller than evt ID requested

- numl.yaml
changes:
- install full `rapids` suite instead of just `cuml`
- add `matplotlib`
- update `numexpr` version
- downgrade `pytorch-cuda` version for compatibility with Heimdall cluster
> update default conda environment

- numl.yaml
Conda environment dependencies get very complicated when incorporating the `cupy` and `cuml` packages from conda-forge. Until this can be resolved, the environment will install these dependencies with pip after the earlier conda packages have been installed.
> install RAPIDS with pip

- numl.yaml
this PR simplifies the standard NuML conda environment in the following ways:
- PyTorch, CUDA and PyG are installed from `conda-forge`, which removes the need for the `pytorch`, `nvidia` and `pyg` channels.
- `cuml` is installed from the `rapidsai` channel instead of from `pip`
- the NuML packages `ph5concat`, `pynuml` and `nugraph` are no longer installed by default. in a development environment, these tagged packages can collide with development versions, which causes a lot of confusion. it is left to the user to install these packages however they see fit.
> update numl conda environment

- nugraph/nugraph/__init__.py
this mechanism was designed to make configuring source code and data directories easier, but in practice it makes things more difficult everywhere except for a couple of UC GPU clusters. the user is still free to set up and use the nugraph environment variables, but they are no longer a condition for importing the module.
> remove setup_env call from import

- nugraph/nugraph/models/nugraph3/nugraph3.py
Will Barrett's tests showed that reducing the number of instance features from 32 to 8 didn't meaningfully change clustering performance, so i'm making that value the default
> reduce number of default instance features to 8

- numl.def
- numl.yaml
this PR adds a definition file that builds a basic apptainer image for the numl environment. added so that @Will-Dallaway0299 can have an apptainer image to run at the Cedar supercomputer cluster
> Add apptainer definition file

- nugraph/nugraph/models/nugraph3/decoders/instance.py
- nugraph/nugraph/models/nugraph3/decoders/spacepoint.py
- nugraph/nugraph/models/nugraph3/encoder.py
- nugraph/nugraph/models/nugraph3/nugraph3.py
- nugraph/nugraph/util/input_norm.py
- pynuml/pynuml/data/nugraph_data.py
silence warnings relating to `num_nodes` for data metadata nodes, which are harmless but annoying. also rework submodules of the NuGraph3 architecture to be `torch.nn.Module` instances instead of `LightningModule` instances, as only the model itself should have that type.
> minor nugraph3 updates

- nugraph/nugraph/data/data_module.py
our IO was optimized for lustre filesystems like those on the Wilson cluster and at NERSC, but these workflows are painfully slow for nodes that use different filesystems. this pull request alleviates this problem by making the number of dataloader processes configurable, and setting it to 5 by default.
> set number of dataloader worker processes

- nugraph/nugraph/models/nugraph2/decoders.py
- nugraph/nugraph/models/nugraph3/decoders/event.py
- nugraph/nugraph/models/nugraph3/decoders/filter.py
- nugraph/nugraph/models/nugraph3/decoders/semantic.py
- nugraph/nugraph/util/__init__.py
- nugraph/nugraph/util/confusion_matrix_logger.py
- scripts/train.py
this PR adds a class `ConfusionMatrixLogger` that abstracts away the process of logging a confusion matrix to either Tensorboard or Weights and Biases. this mean that in both the NuGraph2 and NuGraph3 architectures, the user can instantiate a PyTorch Lightning trainer with either `TensorBoardLogger` or `WandbLogger` and everything should "just work". an additional `--logger` option has been added to the standard training script, which will accept either `wandb` or `tensorboard` as argument. this allows the user to decide whether they prefer to track training metrics using wandb or tensorboard.
> generalize tensorboard and wandb logging

- scripts/train.py
the `--resume` option to the train script was lost a while ago due to some new developments. this PR restores it.
> restore missing --resume option
